version: 2

sphinx:
  builder: html

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.14"
    rust: "1.85"

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
